import os
import argparse
from openai import OpenAI
from dotenv import load_dotenv

load_dotenv()
client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))

def generate_code(prompt):
    response = client.chat.completions.create(
        model="gpt-4o",
        messages=[
            {"role": "system", "content": "Du bist ein Codegenerator für ein modulares Agenten-System. Erstelle sauberen Python-Code mit Struktur, Kommentar und Sinn."},
            {"role": "user", "content": prompt}
        ]
    )
    return response.choices[0].message.content.strip()

def save_file(path, content):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        f.write(content)
    print(f"✅ Datei erstellt: {path}")

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--bot", required=True)
    parser.add_argument("--hub", required=True)
    parser.add_argument("--path", required=True)
    parser.add_argument("--desc", required=True)
    parser.add_argument("--tech", required=True)
    parser.add_argument("--doc", action="store_true")
    parser.add_argument("--test", action="store_true")
    parser.add_argument("--push", action="store_true")
    args = parser.parse_args()

    prompt = f"""Erstelle den Python-Code für einen Bot namens {args.bot}.
Er gehört zum Bereich: {args.hub}.
Funktion: {args.desc}
Verwendete Technologien: {args.tech}

Die Datei soll unter {args.path} gespeichert werden.
Bitte liefere nur den Codeblock – keine Erklärungen.
"""

    # Hauptdatei erzeugen
    code = generate_code(prompt)
    save_file(args.path, code)

    # Testdatei
    if args.test:
        test_path = f"tests/test_{args.bot.lower()}.py"
        test_prompt = f"Erstelle Unit-Tests für den Bot {args.bot}."
        test_code = generate_code(test_prompt)
        save_file(test_path, test_code)

    # Doku-Datei
    if args.doc:
        doc_path = f"docs/modules/{args.bot.lower()}.md"
        doc_prompt = f"Erstelle eine Markdown-Dokumentation für den Bot {args.bot}. Bereich: {args.hub}. Beschreibung: {args.desc}"
        doc_content = generate_code(doc_prompt)
        save_file(doc_path, doc_content)

    # Git push
    if args.push:
        os.system("git add .")
        os.system(f'git commit -m "Add {args.bot} (generated by AION)"')
        os.system("git push")

if __name__ == "__main__":
    main()
